### ISSUE TITLE
しりとりの末尾の処理

### ISSUE THREAD

**Issue by syasin-5d** [syasin-5d/twicas_test#2]
末尾が小文字の場合は大文字に変換しないと詰む
例:「科挙(カキョ)」

**Comment by syasin-5d** [comment]
苦し紛れで「ョーグルト」って送信したらエラーを吐いた

Traceback (most recent call last):
  File "/Users/syasin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/syasin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/syasin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/syasin/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/syasin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/syasin/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 160, in sent
    res = post_comment_with_shiritori(info.movie_id, comment)
  File "app.py", line 93, in post_comment_with_shiritori
    elif text2kana(last_comment)[-1] != text2kana(comment)[0]:
IndexError: string index out of range

**Comment by syasin-5d** [comment]
対応した
